my_quora_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

from qa import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('qa.urls')),
]


urlpatterns += [
    url('^accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    url(r'^accounts/register/$', views.register, name='register'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

qa/urls.py
from django.conf.urls import url
from . import views

app_name = 'qa'  # To use the name in templates as {% url 'qa:index' %}
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^question/create/$', views.question_new, name='new_question'),
    url(r'^question/(?P<pk>[0-9]+)/edit/$', views.question_edit, name='question_edit'),
    url(r'^question/(?P<pk>[0-9]+)/delete/$', views.question_delete, name='question_delete'),
    url(r'^question/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='answers'),
    url(r'^answer/(?P<pk>[0-9]+)/new/$', views.new_answer, name='new_answer'),
    url(r'^answer/(?P<pk>[0-9]+)/edit/$', views.answer_edit, name='answer_edit'),
    url(r'^answer/(?P<pk>[0-9]+)/delete/$', views.answer_delete, name='answer_delete'),
    url(r'^question/(?P<pk>[0-9]+)/vote/$', views.question_vote, name='question_vote'),
    url(r'^answer/(?P<pk>[0-9]+)/vote/$', views.answer_vote, name='answer_vote'),
]

qa/models.py
from django.db import models
from django.contrib.auth.models import User
#  from datetime import datetime
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
#  from django.urls import reverse  # Used to generate URLs by reversing the URL patterns


class Category(models.Model):
    """
    Model representation for category
    """
    name = models.CharField(max_length=200, help_text="Enter the category")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"
        ordering = ["-name"]


class ContentBase(models.Model):
    """
    Abstract Model for contents
    """
    contributor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="%(class)s_contributor")

    total_upvotes = models.IntegerField(default=0, help_text="Total upvotes")
    upvoted_by_users = models.ManyToManyField(User, related_name="%(class)s_upvoted_by_users")

    total_downvotes = models.IntegerField(default=0, help_text="Total downvotes")
    downvoted_by_users = models.ManyToManyField(User, related_name="%(class)s_downvoted_by_users")

    created_at = models.DateTimeField('date created', default=timezone.localtime)
    updated_at = models.DateTimeField('date updated', default=timezone.localtime)

    def __str__(self):
        return self.answer[0:20]

    def upvote(self, user):
        if not self.has_upvoted(user):
            if self.has_downvoted(user):
                self.remove_downvote(user)
            self.upvoted_by_users.add(user)
            self.total_upvotes += 1
            self.save()

    def remove_upvote(self, user):
        self.upvoted_by_users.remove(user)
        self.total_upvotes -= 1
        self.save()

    def downvote(self, user):
        if not self.has_downvoted(user):
            if self.has_upvoted(user):
                self.remove_upvote(user)
            self.downvoted_by_users.add(user)
            self.total_downvotes += 1
            self.save()

    def remove_downvote(self, user):
        self.downvoted_by_users.remove(user)
        self.total_downvotes -= 1
        self.save()

    def has_upvoted(self, user):
        try:
            user = self.upvoted_by_users.get(id=user.id)
            return True if user else False
        except ObjectDoesNotExist:
            return False

    def has_downvoted(self, user):
        try:
            user = self.downvoted_by_users.get(id=user.id)
            return True if user else False
        except ObjectDoesNotExist:
            return False

    class Meta:
        ordering = ["-updated_at"]
        abstract = True


class Question(ContentBase):
    """
    Model representation of an asked question
    """
    subject = models.CharField(max_length=200, help_text="Enter the subject of the question.")
    description = models.TextField(help_text="Enter the description of your question.")
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, help_text="Choose category")

    def __str__(self):
        return self.subject


class Answer(ContentBase):
    """
    Model representation of answer to the asked questions
    """
    question = models.ForeignKey(Question, help_text="Select question", on_delete=models.CASCADE)
    answer = models.TextField(help_text="Enter your answer")

    def __str__(self):
        return self.answer[0:20]

qa/forms.py
from django import forms

from .models import Question, Answer


class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('subject', 'description', 'category',)


class AnswerForm(forms.ModelForm):

    class Meta:
        model = Answer
        fields = ('answer',)

qa/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
#  from django.urls import reverse_lazy
#  from django.views.generic.edit import UpdateView, DeleteView
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone
#  from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
#  from django.contrib.auth.decorators import user_passes_test

import logging

from .models import Question, Answer  # , RateQuestion, RateAnswer
from .forms import QuestionForm, AnswerForm


logger = logging.getLogger(__name__)


class IndexView(generic.ListView):
    model = Question
    template_name = 'qa/index.html'
    context_object_name = 'question_list'
    paginate_by = 6


class DetailView(generic.DetailView):
    model = Question
    template_name = 'qa/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        return context


#  @user_passes_test(lambda u: u.is_anonymous)
def register(request):
    if not request.user.is_authenticated():
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Account Created successfully.")
                return redirect('login')
        else:
            form = UserCreationForm()
    else:
        return HttpResponse("Sorry you are already logged in. To register log out and register a new account!!")
    return render(request, 'registration/register.html', {'form': form})


@login_required
def question_new(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.contributor = request.user
            question.created_at = timezone.now()
            question.updated_at = timezone.now()
            question.save()
            return redirect('qa:answers', pk=question.pk)
    else:
        form = QuestionForm()
    return render(request, 'qa/question_form.html', {'form': form})


@login_required
def question_edit(request, pk):
    question = get_object_or_404(Question, pk=pk, contributor=request.user)
    logger.info(question)
    #  if question.contributor != request.user:
    #      raise PermissionDenied(u"You don't have permission to edit this.")
    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.updated_at = timezone.now()
            question.save()
            return redirect('qa:answers', pk=question.pk)
    else:
        form = QuestionForm(instance=question)
    return render(request, 'qa/question_form.html', {'form': form})


@login_required
def answer_edit(request, pk):
    answer = get_object_or_404(Answer, pk=pk, contributor=request.user)
    #  if answer.contributor != request.user:
    #      raise PermissionDenied(u"You don't have permission to edit this.")

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.updated_at = timezone.now()
            answer.save()
            return redirect('qa:answers', pk=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    return render(request, 'qa/answer_form.html', {'form': form})


@login_required
def question_delete(request, pk):
    question = get_object_or_404(Question, pk=pk, contributor=request.user)
    #  if question.contributor != request.user:
    #      raise PermissionDenied(u"You don't have permission to delete this.")
    question.delete()
    return redirect('qa:index')


@login_required
def answer_delete(request, pk):
    answer = get_object_or_404(Answer, pk=pk, contributor=request.user)
    #  if answer.contributor != request.user:
    #      raise PermissionDenied(u"You don't have permission to delete this.")
    answer.delete()
    return redirect('qa:answers', pk=answer.question.id)


@login_required
def new_answer(request, pk):
    #  import pdb;pdb.set_trace()
    question = Question.objects.get(pk=pk)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question_id = pk
            answer.contributor = request.user
            answer.created_at = timezone.now()
            answer.updated_at = timezone.now()
            answer.save()
            return redirect('qa:answers', pk=question.pk)
    else:
        form = AnswerForm()
    return render(request, 'qa/answer_form.html', {'form': form, 'question': question})


@login_required
def question_vote(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.method == 'POST':
        # Checking which button was clicked
        upvote = True if "upvote" in request.POST else False

        if upvote: question.upvote(request.user)
        else: question.downvote(request.user)

    return redirect('qa:answers', pk=pk)


@login_required
def answer_vote(request, pk):
    answer = get_object_or_404(Answer, pk=pk)
    if request.method == 'POST':
        # Checking which button was clicked
        upvote = True if "upvote" in request.POST else False

        if upvote: answer.upvote(request.user)
        else: answer.downvote(request.user)

    return redirect('qa:answers', pk=answer.question.id)

qa/templates/qa/answer_confirm_delete.html
{% extends "base_generic.html" %}

{% load bootstrap3 %}

{% block content %}

<h1>Delete Question</h1>

<p>Are you sure you want to delete the Answer: {{ answer }}?</p>

<form action="" method="POST">
  {% csrf_token %}

  <!-- <input type="submit" action="" value="Yes, delete." /> -->

      {% buttons %}
        <button type="submit" class="btn btn-danger">
            {# {% bootstrap_icon "arrow" %} #}
            Yes, delete.
        </button>
      {% endbuttons %}


</form>

{% endblock %}

qa/templates/qa/answer_form.html
{% extends "base_generic.html" %}
{% load static %}

{% load bootstrap3 %}

{% block content %}

<form action="" method="post" >

    {% csrf_token %}

<div class="col-sm-6">

    {% bootstrap_form form %}

      {% buttons %}
        <button type="submit" class="btn btn-primary">
            {# {% bootstrap_icon "arrow" %} #} Submit
        </button>
      {% endbuttons %}


    </div>

</form>
{% endblock %}

qa/templates/qa/detail.html
{% extends "base_generic.html" %}

{% load bootstrap3 %}

{% load static %}

{% block content %}

    <h1>{{ question.subject }}</h1>
    <p>{{ question.description }}</p>

    <h4>Asked by: {{ question.contributor.get_username }} </h4>
    <h6>Asked On: {{ question.created_at }}</h6>
    <h6>Updated On: {{ question.updated_at }}</h6>

    <div>
        {% if question.category %}
            <i>#{{ question.category.name }}</i>
        {% else %}
            <i>No category</i>
        {%endif%}
    </div>
    <div>
        <div class="col-sm-12">
            {% if user.is_authenticated  %}
                {% if user.id == question.contributor.id %}

              <a href="{% url 'qa:question_edit' question.id %}">
                <button type="" class="btn btn-primary">
                    {# {% bootstrap_icon "arrow" %} #} Edit
                </button>
              </a>

              <a href="{% url 'qa:question_delete' question.id %}">
                <button type="" class="btn btn-danger">
                    {# {% bootstrap_icon "arrow" %} #} Delete
                </button>
              </a>
                {% endif %}
                </div>

        <div class="col-sm-12">
                <div class="col-sm-2">
                    {% if user in question.upvoted_by_users.all %}
                    <div class="btn-disable btn-default">

                {% else %}
                    <div>
                {% endif %}
                    <form method="post" action="{% url 'qa:question_vote' question.id %}">
                        {% csrf_token %}
                          {% buttons %}
                          <button type="submit" class="btn" name="upvote">
                                {# {% bootstrap_icon "arrow" %} #} Upvote
                            </button>
                          {% endbuttons %}
                    </form>
                </div>
                </div>

                <div class="col-sm-2">
                {% if user in question.downvoted_by_users.all %}
                <div class="btn-disable btn-default">
                {% else %}
                <div>
                {% endif %}


                <form method="post" action="{% url 'qa:question_vote' question.id %}">
                    {% csrf_token %}
                      {% buttons %}
                        <button type="submit" class="btn" name="downvote">
                            {# {% bootstrap_icon "arrow" %} #} Downvote
                        </button>
                      {% endbuttons %}
                </form>
                    </div>
                </div>
            </form>
            {% endif %}
            </div>
                Upvotes: {{question.total_upvotes}}

                Downvotes: {{ question.total_downvotes }}

    {% if question.answer_set.all %}
        <h2>Answers</h2>
        {% for answer in question.answer_set.all %}
            <p> > {{ answer.answer }} by {{ answer.contributor.get_username }}</p>
            <h6>Asked On: {{ answer.created_at }}</h6>
            <h6>Updated On: {{ answer.updated_at }}</h6>

            {% if user.is_authenticated  %}
                {% if user.id == answer.contributor.id %}

            <div>
              <a href="{% url 'qa:answer_edit' answer.id %}">
                <button type="" class="btn btn-primary">
                    {# {% bootstrap_icon "arrow" %} #} Edit
                </button>
              </a>

              <a href="{% url 'qa:answer_delete' answer.id %}">
                <button type="" class="btn btn-danger">
                    {# {% bootstrap_icon "arrow" %} #} Delete
                </button>
              </a>

                </div>

                {% endif %}

                <br/>
            <div class="col-sm-12">
                <div class="col-sm-2">
                    {% if user in answer.upvoted_by_users.all %}
                    <div class="btn-disable btn-default">

                {% else %}
                    <div>
                        {% endif %}
                    <form method="post" action="{% url 'qa:answer_vote' answer.id %}">
                        {% csrf_token %}
                          {% buttons %}
                          <button type="submit" class="btn" name="upvote">
                                {# {% bootstrap_icon "arrow" %} #} Upvote
                            </button>
                          {% endbuttons %}
                    </form>
                </div>
                </div>

                <div class="col-sm-2">
                {% if user in answer.downvoted_by_users.all %}
                <div class="btn-disable btn-default">
                {% else %}
                <div>
                {% endif %}
                <form method="post" action="{% url 'qa:answer_vote' answer.id %}">
                    {% csrf_token %}
                      {% buttons %}
                        <button type="submit" class="btn" name="downvote">
                            {# {% bootstrap_icon "arrow" %} #} Downvote
                        </button>
                      {% endbuttons %}
                </form>
                    </div>
                </div>
            </form>
                </div>


            <br />

            {% endif %}
                Upvotes: {{ answer.total_upvotes }}

                Downvotes: {{answer.total_downvotes}}
        {% endfor %}
    {% else %}
        <i>There is no answer available for this question</i>
    {%endif%}

    {% if user.is_authenticated %}
      {% buttons %}
       <a href="{% url 'qa:new_answer' question.id %}">
        <button type="submit" class="btn btn-default">
            {# {% bootstrap_icon "arrow" %} #} Write an answer
        </button>
       </a>
      {% endbuttons %}
      {% endif %}
    </div>

{% endblock %}

qa/templates/qa/index.html
{% extends "base_generic.html" %}
{% load static %}
{% load bootstrap3 %}

{% block content %}

    {% if question_list %}
        {% for question in question_list %}
            <h3><a href="{% url 'qa:answers' question.id %}">{{ question.subject }}</a> </h3>
            {% if user.is_authenticated  %}
                {% if user.id == question.contributor.id %}

              <a href="{% url 'qa:question_edit' question.id %}">
                <button type="" class="btn btn-primary">
                    {# {% bootstrap_icon "arrow" %} #} Edit
                </button>
              </a>

              <a href="{% url 'qa:question_delete' question.id %}">
                <button type="" class="btn btn-danger">
                    {# {% bootstrap_icon "arrow" %} #} Delete
                </button>
              </a>


                {% endif %}
            {% endif %}

            Upvotes: {{question.total_upvotes}}
            Downvotes: {{question.total_downvotes}}

            <h4>Asked by: {{ question.contributor.get_username }} </h4>
            <i><h5>Total answers: {{ question.answer_set.all.count }}</h5></i>
            {% for answer in question.answer_set.all %} <p>{% if forloop.last %} {{answer.answer}}
                {% endif %}</p>
            {% endfor %}
        {% endfor %}

    {% else %}
        <p>No questions are available.</p>
    {% endif %}
{% endblock %}

qa/templates/qa/question_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Question</h1>

<p>Are you sure you want to delete the Question: {{ question }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

qa/templates/qa/question_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}